# project_config.yml

project:
  name: Package Manager
  description: A Python-based package management system with CLI support.
  version: 1.0.0

dependencies:
  description: List of Python packages required for the project.
  file: requirements.txt
  install_command: |
    pip install -r requirements.txt

instructions:
  running_project:
    description: Instructions for running the project.
    commands:
      - command: PYTHONPATH=. ./bin/package_manager install <package_name>
        description: Install a package.
      - command: PYTHONPATH=. ./bin/package_manager show_installation_packages
        description: Show all installed packages.
      - command: PYTHONPATH=. ./bin/package_manager update <package_name>
        description: Update a package.
      - command: PYTHONPATH=. ./bin/package_manager remove <package_name>
        description: Remove a package.
      - command: PYTHONPATH=. ./bin/package_manager update-repos
        description: Update package repositories.

testing:
  description: Instructions for running tests.
  commands:
    - command: python3 -m unittest discover -s tests -p "test_*.py"
      description: Run all tests in the `tests` directory.

ci_cd:
  description: Configuration for Continuous Integration/Continuous Deployment.
  # Add CI/CD configuration details if applicable
  # Example:
  # build:
  #   image: python:3.9
  #   steps:
  #     - install_dependencies:
  #         command: pip install -r requirements.txt
  #     - run_tests:
  #         command: python3 -m unittest discover -s tests -p "test_*.py"
